To Do list: add & remove
Adholah96/to-do-list pull request #2
Opened 2023-02-23 17:59 UTC by Adholah96

### In this project, I completed the following : 

- [ ] Removed all hardcoded items from the tasks array.

- [ ] Created a new JavaScript file for the new functionality.

- [ ] Implemented a function for adding a new task (add a new element to the array).

- [ ] Implement a function for deleting a task (remove an element from the array).

- [ ] Implemented a function for editing task descriptions.

- [ ] All changes to the To Do List should be saved in local storage.

2023-02-23 18:23 UTC, Zuhaib042 requested changes
Hi @Adholah96  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![close](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights
✅ Professional PR
✅  Correct Github flow

## Required Changes ♻️
- [ ] Good job implementing the adding task and removing task functions. but I cant see the editing task description function. kindly consider implementing editing function as it is one of the requirements.
  -  Implement a function for editing task descriptions.
- [ ] Kindly consider giving your project a meaningful name and descriptive description under the title as it will make your readme more professional.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 04:58 UTC, BenMukebo requested changes
### Hi @Adholah96, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- Function for adding a new book is implemented. ✔️
- Function for remove a book from the array is implemented. ✔️
- GitHub flow is followed. :heavy_check_mark:
- All changes to the To-Do List  are saved in local storage. :heavy_check_mark:


 ## Required Changes ♻️
_Check the comments under the review._

You have submitted a project, that Linters check are not running in the GitHub/action
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Kindly, It will be better to have the issue link in the contributing sections: 

```
## 🤝 Contributing

Feel free to check the [issues page](../../issues/).
```

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 04:58 UTC, BenMukebo commented on modules/app.js
> +export { getData, populateList, addlist };
- [ ] The function of adding and deleting a new book is correctly implemented. However, as requested by the previous reviewer, one of the requirements of the project is that you implement a function for editing book descriptions. Please, address this and make sure that in addition to creating the book, we can also modify its content ✍🏻

2023-02-24 07:12 UTC, Shedrack-Sunday approved these changes
Hi @Adholah96 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


# Highlights
- No linter errors ✔️
- Good implementations ✔️

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-24 07:13 UTC, merged